import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Card from '../components/Card'
import Impact from '../components/Impact'
import Agro from '../components/Agrocommodity'
import Product from '../components/Product'
import bg2 from '../public/assets/Greeenpic.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Greenbles </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <div className='font-rubik'>
          <Header />
          <Hero />
          <Card />
          <Impact />
          <Agro />
          <Product />
          <div className='pt-[89px]  bg-[#F5F1ED]'>
            <div className='max-w-[900px] mx-auto pb-[14px] mb-12'>
              <h1 className='text-center text-4xl pb-12'>Why Greenbles</h1>
              <div className='w-[80%] mx-auto flex items-start flex-wrap justify-between'>
                <div className='w-[30%] mb-10'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    309,156.80
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    acres of farmland cultivated
                  </p>
                </div>

                <div className='w-[30%]'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    71208
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    agriculture enthusiasts & followers
                  </p>
                </div>

                <div className='w-[30%]'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    31770
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    success farmers testimony
                  </p>
                </div>

                <div className='w-[30%]'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    8,000,000
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    raised 8 million chickens with lower than average mortality
                    rate
                  </p>
                </div>

                <div className='w-[30%]'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    1927
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    farmers network
                  </p>
                </div>

                <div className='w-[30%]'>
                  <h1 className='text-tahiti-green text-3xl font-[700] pb-[18px]'>
                    $21m
                  </h1>
                  <p className='font-[350] text-[#5b5b5b] text-md uppercase'>
                    deployed for farming projects in three years
                  </p>
                </div>
              </div>
              {/* <div className='flex gap-[16px] py-[50px]'>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      309,156.80{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md uppercase'>
                      {' '}
                      acres of farmland cultivated
                    </p>
                  </div>
                </div>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      71208{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md uppercase w-2/3'>
                      {' '}
                      Agriculture Enthusiasts & Followers{' '}
                    </p>
                  </div>
                </div>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      31770{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md w-1/2'>
                      {' '}
                      SUCCESS FARMERS TESTIMONY{' '}
                    </p>
                  </div>
                </div>
              </div>

              <div className='flex gap-[16px] py-[50px]'>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      8,000,000{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md uppercase w-2/3'>
                      {' '}
                      raised 8 million chickens with lower than average
                      mortality rate
                    </p>
                  </div>
                </div>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      1927{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md uppercase'>
                      {' '}
                      Farmers network{' '}
                    </p>
                  </div>
                </div>
                <div className='basis-1/3 flex justify-center'>
                  <div className=''>
                    <h1 className=' text-tahiti-green text-3xl font-[700] pb-[18px]'>
                      {' '}
                      $21m{' '}
                    </h1>
                    <p className=' font-[350] text-[#5b5b5b] text-md w-1/2'>
                      {' '}
                      DEPLOYED FOR FARMING PROJECTS IN THREE YEARS{' '}
                    </p>
                  </div>
                </div>
              </div> */}
            </div>

            <div className='bgwall relative'>
              <div className='img_container w-full'>
                <Image src={bg2} className='green_bg' sizes='100vw' />
              </div>
              <div className='max-w-[459px] mx-auto absolute top-1/4 bottom-1/4 left-0 right-0'>
                <h1 className='text-center pb-[47px] text-[#fff] text-lg'>
                  {' '}
                  Donating for Social Impact
                </h1>

                <h2 className=' text-center text-[30px] text-[#fff] pb-[53px]'>
                  {' '}
                  Willing to donate your harvest to the less privileged
                </h2>

                <div className='flex justify-center'>
                  <button className='bg-[#85C226] text-[#fff] w-[150px] h-[30px]'>
                    {' '}
                    Donate Now{' '}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
